### ISSUE TITLE
TypeError: SolanaTracker is not a constructor

### ISSUE THREAD

**Issue by studentofcoding** [YZYLAB/solana-swap#1]
Error when running the example swap code on JS

```
file:///Users/gic_owner/Desktop/Personal/GIC_Capital/Remora/remora-tracker-and-copy-bot/swap_tx.js:7
    const solanaTracker = new SolanaTracker(
                          ^

TypeError: SolanaTracker is not a constructor
    at swap (file:///Users/gic_owner/Desktop/Personal/GIC_Capital/Remora/remora-tracker-and-copy-bot/swap_tx.js:7:27)
    at file:///Users/gic_owner/Desktop/Personal/GIC_Capital/Remora/remora-tracker-and-copy-bot/swap_tx.js:36:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
    ```

**Comment by YZYLAB** [comment]
const SolanaTracker = require("solana-swap").default;
